# This workflow will raise PRs against a set of repos when a release is created.
name: Raise Consumer Pull Requests

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  GEM_NAME: sample_gem
  RUBY_VERSION: 3.3.1

jobs:
  raise_prs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - repo: 'tareks/hello-world-rails'
            appPath: 'hello_world'

    name: 'Raising PR against ${{ matrix.repo }}'
    steps:
      # Checkout the target repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}

      # Configure ruby and use bundler in Gemfile.lock
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: false
          
      - name: Bundle update
        run: |
          cd ${{ matrix.appPath }}
          bundle update ${{ env.GEM_NAME }}
          bundle info ${{ env.GEM_NAME }}

      # Set git configuration
      - name: Set git config
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      # Create a new branch
      - name: Create branch
        run: |
          git checkout -b update-${{ env.GEM_NAME }}-to-${{ github.event.release.tag_name }}
      # Commit changes
      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: bump ${{ env.GEM_NAME }} to ${{ github.event.release.tag_name }}"
          git log
      # Raise a PR aganst target repo

