# This workflow will raise PRs against a set of repos when a release is created.
name: Raise Consumer Pull Requests

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  GEM_NAME: sample_gem
  RUBY_VERSION: 3.3.1
  GEM_VERSION: ${{ github.event.release.tag_name || github.sha }}

jobs:
  raise_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    strategy:
      matrix:
        include:
          - repoOwner: 'tareks'
            repoName: 'hello-world-rails'
            appPath: 'hello_world'

    name: 'Raising PR against ${{ matrix.repoOwner }}/${{ matrix.repoName }}'
    steps:
      # Checkout the target repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repoOwner }}/${{ matrix.repoName }}

      # Configure ruby and use bundler in Gemfile.lock
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: false
          
      - name: Bundle update
        run: |
          cd ${{ matrix.appPath }}
          bundle update ${{ env.GEM_NAME }}
          bundle info ${{ env.GEM_NAME }}

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 938987 # 'tareks-auto-pr-creation-bot'
          private-key: ${{ secrets.GH_APP_AUTO_PR_TOKEN }}
          owner: ${{ matrix.repoOwner }}
          repositories: "${{ matrix.repoName }}"

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Set git config
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'

      # Create Branch and Commit changes
      - name: Commit changes
        id: commit_changes
        run: |
          set -euo pipefail

          cd ${{ matrix.appPath }}
          if [ -n "$(git status Gemfile.lock --porcelain)" ]; then
            git checkout -b update-${{ env.GEM_NAME }}-to-${{ env.GEM_VERSION }}
            git diff Gemfile.lock 
            git add Gemfile.lock
            git commit -m "chore: bump ${{ env.GEM_NAME }} to ${{ env.GEM_VERSION }}"
            echo "Changes committed."     
            git log
            echo "changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes to commit."
            echo "changes=false" >> "$GITHUB_OUTPUT"
          fi

      # Raise a PR aganst target repo only if there are changes to commit
      - name: Raise Pull Request
        if: steps.commit_changes.outputs.changes == 'true'
        run: |
          set -euo pipefail

          # git push origin update-${{ env.GEM_NAME }}-to-${{ env.GEM_VERSION }}
          git branch -a

          gh pr create --title "chore: bump ${{ env.GEM_NAME }} to ${{ env.GEM_VERSION }}" --body "This PR updates ${{ env.GEM_NAME }} to ${{ env.GEM_VERSION }}" --base main --head update-${{ env.GEM_NAME }}-to-${{ env.GEM_VERSION }}      
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}