# This workflow will raise PRs against a set of repos when a release is created.
name: Raise Consumer Pull Requests

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  GEM_NAME: sample_gem
  RUBY_VERSION: 3.3.1
  GEM_VERSION: ${{ github.event.release.tag_name || github.sha }}

jobs:
  raise_prs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - repo: 'tareks/hello-world-rails'
            appPath: 'hello_world'

    name: 'Raising PR against ${{ matrix.repo }}'
    steps:
      # Checkout the target repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}

      # Configure ruby and use bundler in Gemfile.lock
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: false
          
      - name: Bundle update
        run: |
          cd ${{ matrix.appPath }}
          bundle update ${{ env.GEM_NAME }}
          bundle info ${{ env.GEM_NAME }}

      # Set git configuration
      - name: Set git config
        run: |
          cd ${{ matrix.appPath }}
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      # Create a new branch
      - name: Create branch
        run: |
          cd ${{ matrix.appPath }}
          git checkout -b update-${{ env.GEM_NAME }}-to-${{ env.GEM_VERSION }}
      # Commit changes
      - name: Commit changes
        id: commit_changes
        run: |
          cd ${{ matrix.appPath }}
          if [ -n "$(git status Gemfile.lock --porcelain)" ]; then
            git diff Gemfile.lock 
            git add Gemfile.lock
            git commit -m "chore: bump ${{ env.GEM_NAME }} to ${{ env.GEM_VERSION }}"
            echo "Changes committed."
            echo "::set-output name=changes::true"
            git log
          else
            echo "No changes to commit."
            echo "::set-output name=changes::false"
          fi

      # Raise a PR aganst target repo only if there are changes to commit
      - name: Raise Pull Request
        if: steps.commit_changes.outputs.changes == 'true'
        run: |
          cd ${{ matrix.appPath }}
          git push origin update-${{ env.GEM_NAME }}-to-${{ env.GEM_VERSION }}
          gh pr create --title "chore: bump ${{ env.GEM_NAME }} to ${{ env.GEM_VERSION }}" --body "This PR updates ${{ env.GEM_NAME }} to ${{ env.GEM_VERSION }}" --base main --head update-${{ env.GEM_NAME }}-to-${{ env.GEM_VERSION }}      
