name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     bundler-cache: true

      # Bump gem version using release-please-action.
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json

  raise-consumer-prs:
    if: ${{ needs.release.outputs.release_created }}
    needs:
      - release
    permissions:
      contents: write
      packages: write
      pull-requests: write
    uses: ./.github/workflows/raise-consumer-prs.yml
    with:
      gem-version: ${{ needs.release.outputs.tag_name }}
    secrets: inherit
